# this sets the logger level (true = info, false = debug)
production: false
# EigenLayer Slasher contract address

# This is the address of the contracts which are deployed in the anvil saved state
# The saved eigenlayer state is located in tests/anvil/credible_squaring_avs_deployment_output.json
# TODO(samlaf): automate updating these addresses when we deploy new contracts
opacity_avs_address: 0xbfc5d26C6eEb46475eB3960F5373edC5341eE535
avs_directory_address: 0x055733000064333CaDDbC92763c58BF0192fFeBf
chain_id: 17000


# ETH RPC URL
eth_rpc_url: https://ethereum-holesky.publicnode.com

ecdsa_private_key_store_path: <fill in your keystore>
