name: CI to Build and Push Docker Image

on:
  push:
    branches: 
      - "main"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get Commit Hash
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          echo "Building and pushing Docker image..."
          docker build -t opacitylabs/opacity-avs-node:actions-latest -f Dockerfile.dockerignore .
          docker push opacitylabs/opacity-avs-node:actions-latest
